version: '3.8'

services:
  lambda_handler:
    image: terracoil.lambda_handler
    platform: linux/amd64
    build: # "context" and "dockerfile" fields have to be under "build"
      context: .
      dockerfile: Dockerfile.lambda
  fast_api_service:
    image: terracoil.fast_api_service
    platform: linux/amd64
    build: # "context" and "dockerfile" fields have to be under "build"
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "9000:9000"
    volumes:
         - .:/app
         - /app/.venv
    command:
      [
        "uvicorn",
        "--host",
        "0.0.0.0",
        "--port",
        "9000",
        "fast_api_jwt.service.main:app",
        "--reload",
      ]
