[tool.poetry]
name = "fast-api-jwt"
version = "0.1.0"
description = "A sample fast-api service that verifies a JWT with API key."
authors = ["Steven Miers <steven.miers@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.110.0"
uvicorn = {extras = ["standard"], version = "^0.29.0"}
boto3 = "^1.34.71"
python-jose = "^3.3.0"

[tool.poetry.group.dev.dependencies]
poetry-plugin-export = "^1.7.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
